name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
       - feature*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUKCKET_NAME: cfst-3457-6b18bea729fa6610558002d73-nonprodbucket-1u9u3r6j9q8hd
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
           npm ci
           npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUKCKET_NAME }}/ --recursive --acl public-read

